# Generated by Django 5.0.1 on 2024-02-01 17:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
