# Generated by Django 5.0.1 on 2024-02-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_order_products'),
    ]

    operations = []
