# Generated by Django 5.0.1 on 2024-02-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_phone_number'),
    ]

    operations = []
