# Generated by Django 5.0.6 on 2024-07-09 18:22

import store.store_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='', upload_to=store.store_utils.StoreUtils.generate_store_image_path),
            preserve_default=False,
        ),
    ]
