# Generated by Django 5.0.6 on 2024-08-09 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
