# Generated by Django 5.0.6 on 2024-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_on',
            field=models.DateTimeField(null=True),
        ),
    ]
